version: '3.8'
services:
  frontend:
    build: ./
    container_name: frontend_c
    ports:
      - '80:3000'
    volumes:
      - ./:/app
      - /app/node_modules
    stdin_open: true
    tty: true
