export const eng = {
  long_text:
    'You can integrate with E-conomic, Billy, and Dinero using the app. The expenser can submit expenses with their mobile, which go directly into the Cash Journal',
  button_ok: 'Ok',
  login: 'Login',
  request_demo: 'Request Demo',
  registrer_button_uploaded: 'Receipt Uploaded',
  registrer_button_not_uploaded: 'Upload a receipt',
  lorem:
    'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec euismod, nisl Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec euismod, nisl Lorem ipsum dolor sit amet',
  receipt_headers: ['Date', 'Amount', 'Comment', 'Receipt'],
  registrer_modal_info: [
    '1. Receipts and data are sent to the Cash Journal in our accounting program.',
    '2. An email will be sent to you with a receipt.',
    '3. An email will be sent to the accountant about an expense that needs to be processed.',
    "4. You can see your expense in the history under 'History' in the menu.",
  ],
  registrer_modal_title: 'When you click register:',
  frontpage_title: 'Expenses.nu',
  frontpage_subtitle: 'Expense Management Made Simple',
  error: 'Invalid username or password',
  login_page_header: 'Log In',
  login_page_hint: 'Use EMPTY username and password to login as demo user',
  login_page_button: 'Log In',
  historik_page_header: 'Registration History',
  login_page_username: 'Username',
  login_page_password: 'Password',
  registrer_page_header: 'Register Expense',
  receipt_date: 'Receipt Date',
  receipt_amount: 'Amount in DKK',
  commentary: 'Commentary',
  submit_expense: 'Submit Expense',
  close: 'Close',
  how_to_use: 'How to use the app',
  expense_submitted: 'Expense submitted',
  input_number: 'Please input a number',
  category: 'Category',
  categories: [
    'Hotel',
    'Taxi',
    'Catering',
    'Representation',
    'Gifts',
    'Other',
    'Events',
  ],
  default_category: 'Events',
  demo: 'Demo',
  expense_management: 'Demo',
  menu_items_demo: [],
  menu_items: ['Features', 'Pricing', 'About Us'],
  try_it_for_free: 'Try it for Free',
  see_it_in_action: 'See it in action',
  feature_heading: 'RefundVolunteers',
  feature_description:
    'The simple accounting system for smaller unions with volunteers. Integration with e-conomic, Billy and Dinero, you make it easier than ever for volunteer and bookkeeper.',
  try_it: 'Try it',
  read_more: 'Read More',
  cards: [
    {
      heading: 'Integration',
      description:
        'It integrates with Accouting systems such as e-conomic, Billy and Dinero',
      image: 'images/integration_eco_bil_dinero.jpeg',
    },
    {
      heading: 'Automisation',
      description:
        'The receipt goes automatically into the Accouting Software and Bookkeeper is notified',
      image: 'images/cashflow_two.jpeg',
    },
    {
      heading: 'Activities',
      description: 'Less time spend for the volunteers doing expenses',
      image: 'images/easy_activities.jpeg',
    },
    {
      heading: "Excel isn't needed",
      description: 'The volunteer snaps a photo and specifies the amount',
      image: 'images/excel.jpeg',
    },
    {
      heading: 'Overview',
      description:
        'In the overview Section you can see the history of your expenses.',
      image: 'images/overview_receipts.jpeg',
    },
    {
      heading: 'Bookkeeper',
      description:
        'Less manual work for the bookkeeper, due to the integration.',
      image: 'images/Time_saver_accountant_and_person.avif',
    },
  ],
  tiers: [
    {
      title: 'Free',
      price: '0 kr.',
      description: [
        '3 users included',
        'Driving Reembursement',
        'Integrations',
        'Email support',
      ],
      buttonText: 'Sign up for free',
      buttonVariant: 'outlined',
    },
    {
      title: 'Basic',
      subheader: 'Most popular',
      price: '19 kr.',
      description: [
        '10 users included',
        'Driving Reembursement',
        'Integrations',
        'E-mail support',
      ],
      buttonText: 'Get started',
      buttonVariant: 'contained',
    },
    {
      title: 'Premium',
      price: '49 kr.',
      description: [
        '50 users included',
        'Driving Reembursement',
        'Integrations',
        'E-mail support',
      ],
      buttonText: 'Get started',
      buttonVariant: 'outlined',
    },
  ],
  pricing_title: 'Pricing',
  pricing_subtitle:
    'Including all three price levels, there are email support, driving allance and integrations to e-conomic, Billy and Dinero.',
  month: '/mo',

  driving_modal_title: 'Når du klikker Registrer',
  driving_modal_info: [
    '1. The club already has your information, as your login is tied to the membership number.',
    '2. Simply enter “From Address”, “Purpose”, “Date”, and “Kilometers”.',
    '3. An email will be sent to you with a receipt.',
    '4. An email will be sent to the accountant advising of the travel reimbursement.',
  ],
  volunteer_modal_title: "When you click 'Save user'",
  volunteer_modal_info: [
    '1. You create the user in the database.',
    '2. The user receives an email with login information.',
    '3. The accountant receives an email that an account should be created for the user.',
  ],
  driving: 'Driving Reembursement',
  receipt: 'Expence Management',
  volunteer: 'Add a Volunteer',
}
