export const eng = {
  long_text:
    'You can integrate with E-conomic, Billy, and Dinero using the app. The expenser can submit expenses with their mobile, which go directly into the Cash Journal',
  button_ok: 'Ok',
  login: 'Login',
  request_demo: 'Request Demo',
  registrer_button_uploaded: 'Receipt Uploaded',
  registrer_button_not_uploaded: 'Upload a receipt',
  lorem:
    'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec euismod, nisl Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec euismod, nisl Lorem ipsum dolor sit amet',
  receipt_headers: ['Date', 'Amount', 'Comment', 'Receipt'],
  registrer_modal_info: [
    '1. Receipts and data are sent to the Cash Journal in our accounting program.',
    '2. An email will be sent to you with a receipt.',
    '3. An email will be sent to the accountant about an expense that needs to be processed.',
    "4. You can see your expense in the history under 'History' in the menu.",
  ],
  registrer_modal_title: 'When you click register:',
  frontpage_title: 'Expenses.nu',
  frontpage_subtitle: 'Expense Management Made Simple',
  error: 'Invalid username or password',
  login_page_header: 'Log In',
  login_page_hint: 'Use EMPTY username and password to login as demo user',
  login_page_button: 'Log In',
  historik_page_header: 'Registration History',
  login_page_username: 'Username',
  login_page_password: 'Password',
  registrer_page_header: 'Register Expense',
  receipt_date: 'Receipt Date',
  receipt_amount: 'Amount in DKK',
  commentary: 'Commentary',
  submit_expense: 'Submit Expense',
  close: 'Close',
  how_to_use: 'How to use the app',
  expense_submitted: 'Expense submitted',
  input_number: 'Please input a number',
  category: 'Category',
  categories: [
    'Hotel',
    'Taxi',
    'Catering',
    'Representation',
    'Gifts',
    'Other',
    'Events',
  ],
  default_category: 'Events',
  demo: 'Demo',
  expense_management: 'Demo',
  menu_items_demo: [],
  menu_items: ['Features', 'Pricing', 'About Us'],
}
